### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by ticoneva** [jupyterhub/jupyterhub-idle-culler#13]
### Bug description

Running `jupyterhub-idle-culler` on the same server as Jupyterhub with TLS set up. If I use the full URL with https the following error appears:
 ```
tornado.curl_httpclient.CurlError: HTTP 599: SSL certificate problem: unable to get local issuer certificate
```

If I use `http://localhost' then it says:
```
tornado.curl_httpclient.CurlError: HTTP 599: Empty reply from server
```
Certificate works with everything else, including the browser installed on the server.

### Your personal set up

 - OS:
 
 - Version: Ubuntu 20.04.1
 
 - Configuration: jupyterhub 1.0.0

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
