### ISSUE TITLE
Where is file cull_idle_servers.py?

### ISSUE THREAD

**Issue by ghazpar** [jupyterhub/jupyterhub-idle-culler#14]
### Bug description
The documentation in the __init__.py file refers to a file cull_idle_servers.py which does not exist.

#### Expected behaviour
Precise documentation.

#### Actual behaviour
N/A

**Comment by yuvipanda** [comment]
Thanks for catching the discrepancy, @ghazpar! It was left-over from an old migration. #15 should fix it.
