### ISSUE TITLE
Release new version for SSL support

### ISSUE THREAD

**Issue by plockaby** [jupyterhub/jupyterhub-idle-culler#18]
### Proposed change
Release a new version.

### Who would use this feature?
Everyone

### (Optional): Suggest a solution
There are a lot of fixes specifically for SSL support that have been committed but not released. The instructions say to install from pip. I'd like to install from pip and not pull down files from github during my installation process.

Thanks!

**Comment by plockaby** [comment]
I feel like this is _soooo_ close! Is there anything keeping anyone from pressing the final button to do the release?

**Comment by consideRatio** [comment]
![image](https://user-images.githubusercontent.com/3837114/110049814-e6543280-7d52-11eb-9275-5661201621f7.png)

Done!
