### ISSUE TITLE
Time restriction on using jupyterhub

### ISSUE THREAD

**Issue by elham9449** [jupyterhub/jupyterhub-idle-culler#52]
Hi everyone!

Jupyterhub is installed on a server that I am responsible for administering. I would like all users to be restricted to only using Jupyterhub (their notebooks) for 12 hours per day.

I would appreciate your assistance in this matter.

What is its configuration?

**Comment by manics** [comment]
In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Hope you understand 😀.
